spring:
  application:
    name: delivery-tracking
  jpa:
    hibernate:
      ddl-auto: false
    show-sql: false
  datasource:
    url: jdbc:postgresql://localhost:5432/deliverydb
    username: postgres
    password: postgres
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping:
          delivery-placed-event: io.github.cainamott.delivery.tracking.domain.events.DeliveryPlacedEvents,
          delivery-picked-up-event: io.github.cainamott.delivery.tracking.domain.events.DeliveryPickedUpEvent
          delivery-fulfilled-event: io.github.cainamott.delivery.tracking.domain.events.DeliveryFulfilledEvent

eureka:
  client:
    server-url:
      default-zone: http://localhost/8761/eureka/
  instance:
    instance-id: ${random.value}
    prefer-ip-address: true