spring:
  application:
    name: delivery-tracking
  jpa:
    hibernate:
      ddl-auto: false
    show-sql: false
  datasource:
    url: jdbc:postgresql://localhost:5432/deliverydb
    username: postgres
    password: postgres

