spring:
  application:
    name: delivery-tracking
  jpa:
    hibernate:
      ddl-auto: false
    show-sql: false
  datasource:
    url: jdbc:postgresql://localhost:5432/deliverydb
    username: postgres
    password: postgres
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping:
          delivery-placed-event: io.github.cainamott.delivery.tracking.domain.events.DeliveryPlacedEvents,
          delivery-picked-up-event: io.github.cainamott.delivery.tracking.domain.events.DeliveryPickedUpEvent
          delivery-fulfilled-event: io.github.cainamott.delivery.tracking.domain.events.DeliveryFulfilledEvent

eureka:
  client:
    server-url:
      default-zone: http://localhost/8761/eureka/
  instance:
    instance-id: ${random.value}
    prefer-ip-address: true
resilience4j:
  retry:
    configs:
      default:
        maxAttempts: 2
        waitDuration: 20ms
      instances:
        Retry_CourierAPIClient_payoutCalculation:
          baseConfig: default
          maxAttempts: 3
          retryExceptions:
            - org.springframework.web.client.ResourceAccessException
          ignoreExceptions:
            - org.springframework.web.clientHttpServerErrorException

  circuitbreaker:
    configs:
      default:
        slidingWindowType: TIME_BASED
        slidingWindowSize: 5
        minimumNumberOfCalls: 10
        failureRateThreshold: 50
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 10000
    instances:
      CB_CourierAPI_calculatePayout:
        baseConfig: default
        waitDurationInOpenState: 5000
