server.port: 9999

spring:
  application.name: gateway
  cloud:
    gateway.server.webflux:
      httpclient:
        connect-timeout: 10
        response-timeout: 300ms
      routes:
        - id: delivery-tracking-route
          uri: lb://delivery-tracking
          predicates:
            - Path=api/v1/deliveries/**
          filters:
            - name: Retry
              args:
                retries: 3
                statuses: INTERNAL_SERVER_ERROR, BAD_GATEWAY
                method: GET, PUT
                backoff:
                  firstBackoff: 10ms
                  maxBackoff: 30ms
                  factor: 2
                timeout: 400ms
            - name: CircuitBreaker
              args:
                name: delivery-tracking-route-circuit-breaker
                statusCode:
                  - 500
                  - 502
                  - 504

        - id: courier-management-route
          uri: lb://courier-management
          predicates:
            - Path=api/v1/couriers/**

eureka:
  client:
    register-with-eureka: false
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka

resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 5
        minimumNumberOfCalls: 10
        failureRateThreshold: 50
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 10000
    instances:
      delivery-tracking-route-circuit-breaker:
        baseConfig: default
        waitDurationInOpenState: 5000